name: media_file_manager
description: "A specialized media manager for SMB and DLNA."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smb_connect: 0.0.9
  dlna_dart: 0.0.8
  sqflite: ^2.3.0
  media_kit: ^1.1.10
  media_kit_video: ^1.1.4
  media_kit_libs_video: ^1.0.4
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  path_provider: ^2.1.2
  path: ^1.8.3

dependency_overrides:
  collection: 1.18.0
  xml: 6.3.0
